import { Alphabet, LetterIndex, PositionIndex } from "../types";

export const formatWords = (
  words: string[]
): {
  letterIndex: LetterIndex;
  positionIndex: PositionIndex;
} => {
  const { letterIndex, positionIndex } = newFilterWordsObject();

  words.forEach((word) => {
    word.split("").forEach((letter, i) => {
      const index = i + 1;
      letterIndex[letter as Alphabet].add(word);
      positionIndex[index as keyof PositionIndex][letter as Alphabet].add(word);
    });
  });

  return {
    letterIndex,
    positionIndex,
  };
};

const newFilterWordsObject = () => {
  return {
    letterIndex: {
      a: new Set<string>(),
      b: new Set<string>(),
      c: new Set<string>(),
      d: new Set<string>(),
      e: new Set<string>(),
      f: new Set<string>(),
      g: new Set<string>(),
      h: new Set<string>(),
      i: new Set<string>(),
      j: new Set<string>(),
      k: new Set<string>(),
      l: new Set<string>(),
      m: new Set<string>(),
      n: new Set<string>(),
      o: new Set<string>(),
      p: new Set<string>(),
      q: new Set<string>(),
      r: new Set<string>(),
      s: new Set<string>(),
      t: new Set<string>(),
      u: new Set<string>(),
      v: new Set<string>(),
      w: new Set<string>(),
      x: new Set<string>(),
      y: new Set<string>(),
      z: new Set<string>(),
    },
    positionIndex: {
      1: {
        a: new Set<string>(),
        b: new Set<string>(),
        c: new Set<string>(),
        d: new Set<string>(),
        e: new Set<string>(),
        f: new Set<string>(),
        g: new Set<string>(),
        h: new Set<string>(),
        i: new Set<string>(),
        j: new Set<string>(),
        k: new Set<string>(),
        l: new Set<string>(),
        m: new Set<string>(),
        n: new Set<string>(),
        o: new Set<string>(),
        p: new Set<string>(),
        q: new Set<string>(),
        r: new Set<string>(),
        s: new Set<string>(),
        t: new Set<string>(),
        u: new Set<string>(),
        v: new Set<string>(),
        w: new Set<string>(),
        x: new Set<string>(),
        y: new Set<string>(),
        z: new Set<string>(),
      },
      2: {
        a: new Set<string>(),
        b: new Set<string>(),
        c: new Set<string>(),
        d: new Set<string>(),
        e: new Set<string>(),
        f: new Set<string>(),
        g: new Set<string>(),
        h: new Set<string>(),
        i: new Set<string>(),
        j: new Set<string>(),
        k: new Set<string>(),
        l: new Set<string>(),
        m: new Set<string>(),
        n: new Set<string>(),
        o: new Set<string>(),
        p: new Set<string>(),
        q: new Set<string>(),
        r: new Set<string>(),
        s: new Set<string>(),
        t: new Set<string>(),
        u: new Set<string>(),
        v: new Set<string>(),
        w: new Set<string>(),
        x: new Set<string>(),
        y: new Set<string>(),
        z: new Set<string>(),
      },
      3: {
        a: new Set<string>(),
        b: new Set<string>(),
        c: new Set<string>(),
        d: new Set<string>(),
        e: new Set<string>(),
        f: new Set<string>(),
        g: new Set<string>(),
        h: new Set<string>(),
        i: new Set<string>(),
        j: new Set<string>(),
        k: new Set<string>(),
        l: new Set<string>(),
        m: new Set<string>(),
        n: new Set<string>(),
        o: new Set<string>(),
        p: new Set<string>(),
        q: new Set<string>(),
        r: new Set<string>(),
        s: new Set<string>(),
        t: new Set<string>(),
        u: new Set<string>(),
        v: new Set<string>(),
        w: new Set<string>(),
        x: new Set<string>(),
        y: new Set<string>(),
        z: new Set<string>(),
      },
      4: {
        a: new Set<string>(),
        b: new Set<string>(),
        c: new Set<string>(),
        d: new Set<string>(),
        e: new Set<string>(),
        f: new Set<string>(),
        g: new Set<string>(),
        h: new Set<string>(),
        i: new Set<string>(),
        j: new Set<string>(),
        k: new Set<string>(),
        l: new Set<string>(),
        m: new Set<string>(),
        n: new Set<string>(),
        o: new Set<string>(),
        p: new Set<string>(),
        q: new Set<string>(),
        r: new Set<string>(),
        s: new Set<string>(),
        t: new Set<string>(),
        u: new Set<string>(),
        v: new Set<string>(),
        w: new Set<string>(),
        x: new Set<string>(),
        y: new Set<string>(),
        z: new Set<string>(),
      },
      5: {
        a: new Set<string>(),
        b: new Set<string>(),
        c: new Set<string>(),
        d: new Set<string>(),
        e: new Set<string>(),
        f: new Set<string>(),
        g: new Set<string>(),
        h: new Set<string>(),
        i: new Set<string>(),
        j: new Set<string>(),
        k: new Set<string>(),
        l: new Set<string>(),
        m: new Set<string>(),
        n: new Set<string>(),
        o: new Set<string>(),
        p: new Set<string>(),
        q: new Set<string>(),
        r: new Set<string>(),
        s: new Set<string>(),
        t: new Set<string>(),
        u: new Set<string>(),
        v: new Set<string>(),
        w: new Set<string>(),
        x: new Set<string>(),
        y: new Set<string>(),
        z: new Set<string>(),
      },
    },
  };
};
